import { supabase } from './supabase';

export const AIService = {
    askCortex: async (prompt: string) => {
        try {
            // 1. Fetch OpenAI API Key from the API Vault (system_secrets)
            const { data: secretData, error: secretError } = await supabase
                .from('system_secrets')
                .select('value')
                .eq('key', 'OPENAI_API_KEY')
                .single();

            if (secretError || !secretData?.value) {
                return "Error: OPENAI_API_KEY is missing from the API Vault. Please configure it in Settings -> API Vault to activate neural networks.";
            }

            const openAiKey = secretData.value;

            // 2. Fetch context data from the database to give AI real system context
            let contextData = "";
            try {
                // Fetch high level stats to inject as context
                const [users, txns, logs] = await Promise.all([
                    supabase.from('profiles').select('*', { count: 'exact', head: true }),
                    supabase.from('transactions').select('amount').limit(100),
                    supabase.from('audit_logs').select('*', { count: 'exact', head: true })
                ]);
                
                const totalTxns = txns.data?.reduce((sum, t) => sum + Number(t.amount), 0) || 0;
                contextData = `System Context: You are Cortex AI, the Super Admin assistant for ABU-MAFHAL-HUB. Currently there are ${users.count || 0} registered users. Total throughput from recent transactions is ₦${totalTxns}. There are ${logs.count || 0} audit logs recorded. Answer professionally and concisely.`;
            } catch (e) {
                contextData = "System Context: You are Cortex AI, the Super Admin assistant. Answer professionally and concisely.";
            }

            // 3. Make real OpenAI API call
            const response = await fetch('https://api.openai.com/v1/chat/completions', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${openAiKey}`
                },
                body: JSON.stringify({
                    model: 'gpt-4o-mini', // Fast, intelligent model
                    messages: [
                        { role: 'system', content: contextData },
                        { role: 'user', content: prompt }
                    ],
                    temperature: 0.7,
                    max_tokens: 300
                })
            });

            if (!response.ok) {
                const errResult = await response.json();
                throw new Error(errResult.error?.message || 'Failed to communicate with OpenAI API.');
            }

            const result = await response.json();
            return result.choices[0]?.message?.content || "No response generated by the neural network.";

        } catch (e: any) {
            console.error('Cortex AI Error:', e);
            return `System Error: ${e.message}`;
        }
    }
};
