import { View, Text, TouchableOpacity, ScrollView, StyleSheet, Animated, ActivityIndicator, Alert, Modal, TextInput, Share, Vibration, Image, Dimensions, Platform } from 'react-native';
import { Stack, useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { StatusBar } from 'expo-status-bar';
import { useState, useEffect, useRef } from 'react';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { supabase } from '../services/supabase';
import { LinearGradient } from 'expo-linear-gradient';
import { BlurView } from 'expo-blur';
import SecurityModal from '../components/SecurityModal';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';

const T = {
  navy:    '#0d1b3e',
  navyMid: '#142258',
  gold:    '#f5a623',
  goldDk:  '#d4890e',
  white:   '#ffffff',
  bg:      '#f4f6fb',
  text:    '#0d1b3e',
  textSub: '#5a6890',
  indigo:  '#4F46E5',
};

export default function QRPayScreen() {
    const router = useRouter();
    const [activeTab, setActiveTab] = useState<'scan' | 'mycode'>('scan');
    const [permission, requestPermission] = useCameraPermissions();
    const [torchEnabled, setTorchEnabled] = useState(false);
    const [scanned, setScanned] = useState(false);
    
    // User data
    const [currentUser, setCurrentUser] = useState<any>(null);
    const [userBalance, setUserBalance] = useState(0);
    
    // Transaction UI states
    const [scannedUser, setScannedUser] = useState<any>(null);
    const [confirmModalVisible, setConfirmModalVisible] = useState(false);
    const [securityModalVisible, setSecurityModalVisible] = useState(false);
    const [successModalVisible, setSuccessModalVisible] = useState(false);
    const [isSubmitting, setIsSubmitting] = useState(false);
    
    // Manual Input states
    const [manualInputVisible, setManualInputVisible] = useState(false);
    const [manualInput, setManualInput] = useState('');
    const [isVerifyingManual, setIsVerifyingManual] = useState(false);
    
    // Form Inputs
    const [amount, setAmount] = useState('');
    const [description, setDescription] = useState('');

    // Scanner animation
    const scanLineAnim = useRef(new Animated.Value(0)).current;

    useEffect(() => {
        loadUserProfile();
    }, []);

    useEffect(() => {
        if (activeTab === 'scan' && permission?.granted && !scanned) {
            // Laser line looping animation
            scanLineAnim.setValue(0);
            Animated.loop(
                Animated.sequence([
                    Animated.timing(scanLineAnim, {
                        toValue: 240,
                        duration: 2500,
                        useNativeDriver: true,
                    }),
                    Animated.timing(scanLineAnim, {
                        toValue: 0,
                        duration: 2500,
                        useNativeDriver: true,
                    })
                ])
            ).start();
        } else {
            scanLineAnim.stopAnimation();
        }
    }, [activeTab, permission, scanned]);

    const loadUserProfile = async () => {
        try {
            const { data: { user } } = await supabase.auth.getUser();
            if (user) {
                const { data: profile } = await supabase
                    .from('profiles')
                    .select('id, full_name, email, balance')
                    .eq('id', user.id)
                    .single();
                if (profile) {
                    setCurrentUser(profile);
                    setUserBalance(parseFloat(profile.balance || '0'));
                }
            }
        } catch (e) {
            console.error("Error loading user profile:", e);
        }
    };

    const handleShareMyCode = async () => {
        if (!currentUser) return;
        
        // 1. Construct the flyer URL hosted on Vercel
        const domain = Platform.OS === 'web' ? window.location.origin : 'https://abumafhal.com.ng';
        const flyerUrl = `${domain}/flyer-template?name=${encodeURIComponent(currentUser.full_name)}&email=${encodeURIComponent(currentUser.email)}&userId=${currentUser.id}`;
        
        // 2. Fetch the screenshot image generated by thum.io
        const thumIoUrl = `https://image.thum.io/get/width/600/crop/800/maxAge/12/${flyerUrl}`;

        try {
            if (Platform.OS === 'web') {
                // On Web, trigger a download of the flyer PNG image
                setIsSubmitting(true);
                const response = await fetch(thumIoUrl);
                const blob = await response.blob();
                const blobUrl = URL.createObjectURL(blob);
                
                const link = document.createElement('a');
                link.href = blobUrl;
                link.download = `mafhal_pay_flyer_${currentUser.full_name.replace(/\s+/g, '_')}.png`;
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link);
                URL.revokeObjectURL(blobUrl);
                setIsSubmitting(false);
            } else {
                // On Mobile (Android/iOS), download the flyer image to Cache, then share as a real image file!
                const fileUri = `${FileSystem.cacheDirectory}mafhal_pay_flyer_${currentUser.id}.png`;
                
                setIsSubmitting(true);
                const { uri } = await FileSystem.downloadAsync(thumIoUrl, fileUri);
                setIsSubmitting(false);

                // Share the downloaded flyer image file
                await Sharing.shareAsync(uri, {
                    mimeType: 'image/png',
                    dialogTitle: `Pay ${currentUser.full_name} - Mafhal Hub`,
                });
            }
        } catch (error: any) {
            setIsSubmitting(false);
            console.error("Flyer share error:", error);
            // Fallback to text sharing if file sharing/download fails
            try {
                await Share.share({
                    title: `Pay ${currentUser.full_name}`,
                    message: `Assalamu alaikum, scan this QR code or use my email to send me money instantly on Mafhal Hub:\n\n👤 Name: ${currentUser.full_name}\n📧 Email: ${currentUser.email}\n\n🔗 View QR Flyer: ${thumIoUrl}`,
                });
            } catch (fallbackError: any) {
                Alert.alert("Share Error", fallbackError.message);
            }
        }
    };

    const onBarcodeScanned = async ({ data }: { data: string }) => {
        if (scanned || confirmModalVisible || successModalVisible) return;
        setScanned(true);
        Vibration.vibrate(100);
        
        try {
            let userId = '';
            let email = '';
            
            try {
                const parsed = JSON.parse(data);
                if (parsed.userId) {
                    userId = parsed.userId;
                    email = parsed.email || '';
                }
            } catch (jsonErr) {
                const trimmedData = data.trim();
                if (trimmedData.includes('@')) {
                    email = trimmedData.toLowerCase();
                } else if (trimmedData.length === 36) {
                    userId = trimmedData;
                } else {
                    email = trimmedData.toLowerCase();
                }
            }

            let query = supabase.from('profiles').select('id, full_name, email');
            if (userId) {
                query = query.eq('id', userId);
            } else if (email) {
                query = query.eq('email', email);
            } else {
                Alert.alert("Invalid QR", "This QR code does not contain a valid user ID or email.", [
                    { text: "OK", onPress: () => setScanned(false) }
                ]);
                return;
            }

            const { data: recipient, error } = await query.maybeSingle();
            
            if (error || !recipient) {
                Alert.alert("User Not Found", "No registered user was found matching this QR code.", [
                    { text: "OK", onPress: () => setScanned(false) }
                ]);
                return;
            }

            if (currentUser && recipient.id === currentUser.id) {
                Alert.alert("Scan Error", "You cannot transfer money to yourself!", [
                    { text: "OK", onPress: () => setScanned(false) }
                ]);
                return;
            }

            setScannedUser({
                userId: recipient.id,
                name: recipient.full_name,
                email: recipient.email
            });
            setConfirmModalVisible(true);
        } catch (err: any) {
            Alert.alert("Scan Error", "Failed to process QR code details.", [
                { text: "OK", onPress: () => setScanned(false) }
            ]);
        }
    };

    const handleVerifyManualRecipient = async () => {
        if (!manualInput) {
            Alert.alert("Error", "Please enter an email address.");
            return;
        }
        
        setIsVerifyingManual(true);
        try {
            // Call Supabase RPC find_profile_by_email to safely query recipient bypassing RLS constraints
            const { data: recipient, error } = await supabase.rpc('find_profile_by_email', {
                email_query: manualInput.trim().toLowerCase()
            });
                
            if (error) throw error;
            
            if (!recipient) {
                Alert.alert("Not Found", "No user found with this email address. Please make sure the email is typed correctly.");
                return;
            }

            if (currentUser && recipient.id === currentUser.id) {
                Alert.alert("Error", "You cannot transfer money to yourself!");
                return;
            }

            setScannedUser({
                userId: recipient.id,
                name: recipient.full_name,
                email: recipient.email
            });
            setManualInputVisible(false);
            setManualInput('');
            setConfirmModalVisible(true);
        } catch (e: any) {
            Alert.alert("Verification Failed", e.message || "An error occurred.");
        } finally {
            setIsVerifyingManual(false);
        }
    };

    const handleConfirmTransfer = async () => {
        if (!amount || parseFloat(amount) <= 0) {
            Alert.alert("Invalid Amount", "Please enter a valid amount.");
            return;
        }

        const transferAmt = parseFloat(amount);
        if (transferAmt > userBalance) {
            Alert.alert("Insufficient Balance", `Your balance is ₦${userBalance.toLocaleString()}, which is less than ₦${transferAmt.toLocaleString()}.`);
            return;
        }

        setConfirmModalVisible(false);
        setSecurityModalVisible(true);
    };

    const executeTransfer = async () => {
        setSecurityModalVisible(false);
        setIsSubmitting(true);
        
        try {
            const transferAmt = parseFloat(amount);
            const senderId = currentUser.id;
            const recipientId = scannedUser.userId;

            // Call Supabase RPC execute_wallet_transfer to perform the double-entry transaction atomically on the backend
            const { data, error } = await supabase.rpc('execute_wallet_transfer', {
                sender_id: senderId,
                target_id: recipientId,
                amount: transferAmt,
                note: description
            });

            if (error) throw error;

            Vibration.vibrate([0, 100, 50, 100]);
            
            // Refresh local balance
            await loadUserProfile();
            
            setSuccessModalVisible(true);
        } catch (e: any) {
            Alert.alert("Transfer Failed", e.message || "An error occurred during payment.");
            setScanned(false);
        } finally {
            setIsSubmitting(false);
        }
    };

    const handleSuccessDone = () => {
        setSuccessModalVisible(false);
        setAmount('');
        setDescription('');
        setScanned(false);
        setScannedUser(null);
        router.replace('/(app)/dashboard');
    };

    if (!permission) {
        return (
            <View className="flex-1 bg-white items-center justify-center">
                <ActivityIndicator size="large" color="#0056D2" />
            </View>
        );
    }

    // Build user QR code payload
    const myCodePayload = currentUser ? JSON.stringify({
        type: 'transfer',
        userId: currentUser.id,
        name: currentUser.full_name,
        email: currentUser.email
    }) : '';

    return (
        <View className="flex-1 bg-[#f4f6fb]">
            <Stack.Screen options={{ headerShown: false }} />
            <StatusBar style="light" />

            {/* Premium Curved Header */}
            <LinearGradient 
              colors={['#060d21', '#0d1b3e']} 
              style={s.headerContainer}
            >
              <View style={s.headerTop}>
                <TouchableOpacity onPress={() => router.back()} style={s.backBtn}>
                  <Ionicons name="arrow-back" size={20} color="white" />
                </TouchableOpacity>
                <Text style={s.headerTitle}>QR Payment</Text>
                <View style={{ width: 32 }} />
              </View>

              {/* Tab Switcher */}
              <View style={s.tabContainer}>
                <TouchableOpacity
                    onPress={() => setActiveTab('scan')}
                    style={[s.tabItem, activeTab === 'scan' && s.tabItemActive]}
                >
                    <Text style={[s.tabText, activeTab === 'scan' && s.tabTextActive]}>Scan Code</Text>
                </TouchableOpacity>
                <TouchableOpacity
                    onPress={() => setActiveTab('mycode')}
                    style={[s.tabItem, activeTab === 'mycode' && s.tabItemActive]}
                >
                    <Text style={[s.tabText, activeTab === 'mycode' && s.tabTextActive]}>My QR Code</Text>
                </TouchableOpacity>
              </View>
            </LinearGradient>

            {activeTab === 'scan' ? (
                <View style={{ flex: 1, marginTop: -16 }}>
                    {!permission.granted ? (
                        <View style={s.permissionCard}>
                            <View style={s.permissionIconWrapper}>
                                <Ionicons name="camera-outline" size={48} color="#0056D2" />
                            </View>
                            <Text style={s.permissionTitle}>Camera Access Required</Text>
                            <Text style={s.permissionDesc}>
                                We need access to your camera to scan QR codes for instant wallet payments.
                            </Text>
                            
                            <TouchableOpacity 
                                onPress={requestPermission}
                                style={s.grantBtn}
                                activeOpacity={0.9}
                            >
                                <LinearGradient colors={['#0056D2', '#1e40af']} style={s.gradientBtn} start={{x:0, y:0}} end={{x:1, y:0}}>
                                    <Text style={s.grantBtnText}>Grant Permission</Text>
                                </LinearGradient>
                            </TouchableOpacity>

                            <TouchableOpacity 
                                onPress={() => setManualInputVisible(true)}
                                className="mt-5"
                                activeOpacity={0.7}
                            >
                                <Text style={s.manualLinkText}>Or Enter Email Manually</Text>
                            </TouchableOpacity>
                        </View>
                    ) : (
                        <View className="flex-1 bg-black relative">
                            {scanned ? (
                                <View className="flex-1 items-center justify-center bg-black/80">
                                    <ActivityIndicator size="large" color="#f5a623" />
                                    <Text className="text-white font-bold mt-4">Processing scan...</Text>
                                </View>
                            ) : (
                                <CameraView
                                    style={StyleSheet.absoluteFillObject}
                                    facing="back"
                                    enableTorch={torchEnabled}
                                    onBarcodeScanned={onBarcodeScanned}
                                    barcodeScannerSettings={{
                                        barcodeTypes: ["qr"],
                                    }}
                                />
                            )}

                            {/* Viewfinder overlay */}
                            {!scanned && (
                                <View style={s.overlayContainer}>
                                    <View style={s.overlayTop} />
                                    <View style={s.overlayMiddle}>
                                        <View style={s.overlaySide} />
                                        <View style={s.scanWindow}>
                                            <View style={[s.corner, s.topLeft]} />
                                            <View style={[s.corner, s.topRight]} />
                                            <View style={[s.corner, s.bottomLeft]} />
                                            <View style={[s.corner, s.bottomRight]} />
                                            
                                            <Animated.View style={[s.laserLine, { transform: [{ translateY: scanLineAnim }] }]} />
                                        </View>
                                        <View style={s.overlaySide} />
                                    </View>
                                    <View style={s.overlayBottom}>
                                        <Text style={s.overlayText}>Align the QR code within the frame to pay</Text>
                                        
                                        <View className="flex-row gap-4 px-6 justify-center w-full">
                                            <TouchableOpacity 
                                                onPress={() => setTorchEnabled(!torchEnabled)}
                                                style={s.torchBtn}
                                                activeOpacity={0.8}
                                            >
                                                <Ionicons name={torchEnabled ? "flash" : "flash-off"} size={16} color="white" />
                                                <Text style={s.torchBtnText}>{torchEnabled ? "Flash On" : "Flash Off"}</Text>
                                            </TouchableOpacity>

                                            <TouchableOpacity 
                                                onPress={() => setManualInputVisible(true)}
                                                style={s.torchBtn}
                                                activeOpacity={0.8}
                                            >
                                                <Ionicons name="create-outline" size={16} color="white" />
                                                <Text style={s.torchBtnText}>Enter Email</Text>
                                            </TouchableOpacity>
                                        </View>
                                    </View>
                                </View>
                            )}
                        </View>
                    )}
                </View>
            ) : (
                <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24, marginTop: -16 }}>
                    {currentUser ? (
                        <LinearGradient 
                            colors={['#102258', '#0b163a']} 
                            style={s.myCodeCard}
                            start={{ x: 0, y: 0 }}
                            end={{ x: 1, y: 1 }}
                        >
                            {/* Watermark Logo */}
                            <View style={s.myCodeWatermark}>
                                <Image source={require('../assets/images/logo.png')} style={{ width: '100%', height: '100%', opacity: 0.05 }} resizeMode="contain" />
                            </View>

                            <View style={s.myCodeHeader}>
                                <View style={s.avatarWrapper}>
                                    <Ionicons name="person" size={24} color="#0056D2" />
                                </View>
                                <View style={{ marginLeft: 12 }}>
                                    <Text style={s.myCodeName}>{currentUser.full_name}</Text>
                                    <Text style={s.myCodeEmail}>{currentUser.email}</Text>
                                </View>
                            </View>

                            {/* Live QR Code Box */}
                            <View style={s.qrWrapper}>
                                <Image
                                    source={{ uri: `https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=${encodeURIComponent(myCodePayload)}&color=0d1b3e` }}
                                    style={{ width: 170, height: 170 }}
                                    resizeMode="contain"
                                />
                            </View>

                            <Text style={s.qrHintText}>
                                Scan this code to send money to this wallet instantly.
                            </Text>

                            <TouchableOpacity 
                                onPress={handleShareMyCode}
                                style={s.shareBtn}
                                activeOpacity={0.9}
                            >
                                <Ionicons name="share-social-outline" size={16} color={T.navy} />
                                <Text style={s.shareBtnText}>Share My Code</Text>
                            </TouchableOpacity>
                        </LinearGradient>
                    ) : (
                        <ActivityIndicator size="large" color="#0056D2" />
                    )}
                </View>
            )}

            {/* CONFIRM / AMOUNT INPUT MODAL */}
            <Modal visible={confirmModalVisible} transparent animationType="slide">
                <View className="flex-1 justify-end bg-black/60">
                    <View className="bg-white rounded-t-[36px] p-6 pb-10">
                        {/* Drag Handle */}
                        <View className="w-10 h-1 bg-slate-200 rounded-full self-center mb-6" />

                        <Text className="text-center font-black text-slate-800 text-lg mb-6">Send Money via QR</Text>

                        {scannedUser && (
                            <View className="flex-row items-center bg-[#f4f6fb] p-4 rounded-2xl mb-6 border border-gray-100">
                                <View className="w-12 h-12 rounded-full bg-blue-100 items-center justify-center mr-4">
                                    <Text className="font-black text-blue-700 text-lg">{scannedUser.name[0]}</Text>
                                </View>
                                <View className="flex-1">
                                    <Text className="font-black text-slate-800 text-base">{scannedUser.name}</Text>
                                    <Text className="text-slate-400 text-xs font-semibold">{scannedUser.email}</Text>
                                </View>
                            </View>
                        )}

                        {/* Amount */}
                        <Text className="text-slate font-black text-xs uppercase tracking-wider mb-2">Amount to Send</Text>
                        <View className="flex-row items-center border border-slate-200 rounded-2xl px-4 h-16 bg-slate-50 mb-2">
                            <Text className="text-slate-500 text-xl font-bold mr-2">₦</Text>
                            <TextInput
                                className="flex-1 text-2xl font-black text-slate-800"
                                keyboardType="number-pad"
                                value={amount}
                                onChangeText={setAmount}
                                placeholder="0.00"
                                placeholderTextColor="#cbd5e1"
                            />
                        </View>
                        <Text className="text-slate-400 text-xs font-semibold mb-6">
                            Available Balance: <Text className="text-[#0056D2] font-black">₦{userBalance.toLocaleString()}</Text>
                        </Text>

                        {/* Description */}
                        <Text className="text-slate font-black text-xs uppercase tracking-wider mb-2">Note (Optional)</Text>
                        <TextInput
                            className="border border-slate-200 rounded-2xl px-4 py-3 text-slate-800 bg-slate-50 mb-8 font-semibold"
                            value={description}
                            onChangeText={setDescription}
                            placeholder="Add a payment note"
                            placeholderTextColor="#cbd5e1"
                        />

                        {/* Action buttons */}
                        <View className="flex-row gap-4">
                            <TouchableOpacity 
                                onPress={() => { setConfirmModalVisible(false); setScanned(false); }}
                                className="flex-1 h-14 bg-slate-100 rounded-2xl items-center justify-center border border-slate-200"
                            >
                                <Text className="text-slate-600 font-bold text-base">Cancel</Text>
                            </TouchableOpacity>
                            <TouchableOpacity 
                                onPress={handleConfirmTransfer}
                                className="flex-1 h-14 bg-[#0056D2] rounded-2xl items-center justify-center shadow-lg"
                            >
                                <Text className="text-white font-bold text-base">Continue</Text>
                            </TouchableOpacity>
                        </View>
                    </View>
                </View>
            </Modal>

            {/* GLASSMORPHIC MANUAL RECIPIENT INPUT MODAL */}
            <Modal visible={manualInputVisible} transparent animationType="fade" onRequestClose={() => setManualInputVisible(false)}>
                <View style={s.modalOverlay}>
                    <BlurView intensity={90} tint="dark" style={StyleSheet.absoluteFillObject} />
                    
                    <Animated.View style={s.modalCard}>
                        {/* Drag indicator */}
                        <View style={s.modalPill} />

                        <View style={s.modalHeaderWrapper}>
                            <View style={s.modalIconWrapper}>
                                <Ionicons name="mail" size={22} color="#0056D2" />
                            </View>
                            <View style={{ marginLeft: 12 }}>
                                <Text style={s.modalTitle}>Enter Recipient</Text>
                                <Text style={s.modalSub}>Type the registered user email address.</Text>
                            </View>
                        </View>

                        {/* Text Input */}
                        <Text style={s.inputLabel}>Recipient Email</Text>
                        <View style={s.inputContainer}>
                            <Ionicons name="mail-outline" size={20} color="#94a3b8" style={{ marginRight: 10 }} />
                            <TextInput
                                style={s.textInput}
                                keyboardType="email-address"
                                autoCapitalize="none"
                                value={manualInput}
                                onChangeText={setManualInput}
                                placeholder="name@domain.com"
                                placeholderTextColor="#cbd5e1"
                            />
                        </View>

                        {/* Actions */}
                        <View style={s.btnRow}>
                            <TouchableOpacity 
                                onPress={() => { setManualInputVisible(false); setManualInput(''); }}
                                style={s.cancelBtn}
                                activeOpacity={0.7}
                            >
                                <Text style={s.cancelBtnText}>Cancel</Text>
                            </TouchableOpacity>
                            
                            <TouchableOpacity 
                                onPress={handleVerifyManualRecipient}
                                style={s.actionBtn}
                                disabled={isVerifyingManual}
                                activeOpacity={0.9}
                            >
                                <LinearGradient colors={['#0056D2', '#1e40af']} style={s.actionBtnGradient} start={{x:0, y:0}} end={{x:1, y:0}}>
                                    {isVerifyingManual ? (
                                        <ActivityIndicator color="white" size="small" />
                                    ) : (
                                        <>
                                            <Text style={s.actionBtnText}>Verify User</Text>
                                            <Ionicons name="checkmark-circle-outline" size={16} color="white" style={{ marginLeft: 4 }} />
                                        </>
                                    )}
                                </LinearGradient>
                            </TouchableOpacity>
                        </View>
                    </Animated.View>
                </View>
            </Modal>

            {/* SECURITY VERIFICATION MODAL */}
            <SecurityModal
                visible={securityModalVisible}
                onClose={() => { setSecurityModalVisible(false); setScanned(false); }}
                onSuccess={executeTransfer}
                title="Verify PIN"
                description="Enter transaction PIN to authorize QR payment."
            />

            {/* TRANSACTION SUCCESS MODAL */}
            <Modal visible={successModalVisible} transparent animationType="fade">
                <View className="flex-1 bg-black/60 items-center justify-center p-6">
                    <View className="bg-white rounded-[32px] p-6 items-center w-full max-w-[340px] shadow-2xl relative overflow-hidden">
                        {/* Decorative background shapes */}
                        <View className="absolute -top-10 -left-10 w-24 h-24 bg-green-50 rounded-full" />
                        
                        <View className="w-20 h-20 bg-emerald-100 rounded-full items-center justify-center mb-6 shadow-inner mt-4">
                            <Ionicons name="checkmark-circle" size={48} color="#107C10" />
                        </View>

                        <Text className="text-xl font-black text-slate-800 mb-2">Transfer Successful!</Text>
                        <Text className="text-slate-400 text-xs font-semibold mb-6 uppercase tracking-wider text-center">Receipt</Text>

                        {/* Receipt details */}
                        <View className="w-full bg-slate-50 p-4 rounded-2xl mb-8 border border-slate-100">
                            <View className="flex-row justify-between mb-3">
                                <Text className="text-slate-400 text-xs font-semibold">Sent Amount</Text>
                                <Text className="text-slate-800 font-black text-sm">₦{parseFloat(amount).toLocaleString(undefined, { minimumFractionDigits: 2 })}</Text>
                            </View>
                            <View className="flex-row justify-between mb-3">
                                <Text className="text-slate-400 text-xs font-semibold">Recipient</Text>
                                <Text className="text-slate-800 font-black text-sm">{scannedUser?.name}</Text>
                            </View>
                            <View className="flex-row justify-between">
                                <Text className="text-slate-400 text-xs font-semibold">Method</Text>
                                <Text className="text-slate-800 font-black text-sm">QR Code / Manual Email</Text>
                            </View>
                        </View>

                        <TouchableOpacity 
                            onPress={handleSuccessDone}
                            className="w-full bg-[#107C10] h-14 rounded-2xl items-center justify-center shadow-lg active:bg-green-700"
                        >
                            <Text className="text-white font-bold text-base">Done</Text>
                        </TouchableOpacity>
                    </View>
                </View>
            </Modal>

            {/* Global Loader overlay for submissions */}
            {isSubmitting && (
                <View className="absolute inset-0 bg-black/60 items-center justify-center z-50">
                    <View className="bg-white p-6 rounded-2xl flex-row items-center gap-4 border border-gray-100 shadow-xl">
                        <ActivityIndicator size="small" color="#0056D2" />
                        <Text className="text-slate-800 font-bold">Executing transaction...</Text>
                    </View>
                </View>
            )}
        </View>
    );
}

const s = StyleSheet.create({
  // Curved header
  headerContainer: {
    paddingHorizontal: 20,
    paddingTop: 48,
    paddingBottom: 36,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    zIndex: 20,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  backBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: 'white',
    letterSpacing: -0.2,
  },
  // Tab bar
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 14,
    padding: 2,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  tabItem: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 12,
  },
  tabItemActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
  },
  tabText: {
    fontSize: 11,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.5)',
  },
  tabTextActive: {
    color: 'white',
    fontWeight: '900',
  },
  // Permission Card
  permissionCard: {
    flex: 1,
    backgroundColor: 'white',
    borderRadius: 24,
    margin: 20,
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#e2e5ef',
    shadowColor: 'rgba(13,27,62,0.04)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 2,
  },
  permissionIconWrapper: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(0,86,210,0.05)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  permissionTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: T.navy,
    marginBottom: 8,
  },
  permissionDesc: {
    fontSize: 13,
    color: T.textSub,
    textAlign: 'center',
    lineHeight: 18,
    paddingHorizontal: 16,
    marginBottom: 28,
  },
  grantBtn: {
    width: '100%',
    maxWidth: 240,
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: '#0056D2',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3,
  },
  gradientBtn: {
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  grantBtnText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '800',
  },
  manualLinkText: {
    color: '#0056D2',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  // My Code Card
  myCodeCard: {
    width: '100%',
    maxWidth: 340,
    borderRadius: 30,
    padding: 24,
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
    shadowColor: '#0d1b3e',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 8,
  },
  myCodeWatermark: {
    position: 'absolute',
    right: -20,
    bottom: -20,
    width: 150,
    height: 150,
  },
  myCodeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'stretch',
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.06)',
    paddingBottom: 16,
  },
  avatarWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  myCodeName: {
    fontSize: 16,
    fontWeight: '900',
    color: 'white',
    letterSpacing: -0.3,
  },
  myCodeEmail: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.5)',
    fontWeight: '600',
    marginTop: 1,
  },
  qrWrapper: {
    padding: 16,
    backgroundColor: 'white',
    borderRadius: 24,
    marginBottom: 20,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  qrHintText: {
    fontSize: 9,
    color: 'rgba(255,255,255,0.4)',
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    textAlign: 'center',
    paddingHorizontal: 16,
    marginBottom: 20,
    lineHeight: 13,
  },
  shareBtn: {
    width: '100%',
    backgroundColor: T.gold,
    paddingVertical: 12,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: T.gold,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 2,
  },
  shareBtnText: {
    fontSize: 12,
    fontWeight: '800',
    color: T.navy,
    marginLeft: 6,
  },
  // Modal layout
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.55)',
    padding: 24,
  },
  modalCard: {
    width: '100%',
    maxWidth: 340,
    backgroundColor: 'white',
    borderRadius: 30,
    padding: 24,
    shadowColor: 'black',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 8,
    position: 'relative',
  },
  modalPill: {
    width: 36,
    height: 4,
    backgroundColor: '#e2e5ef',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 16,
  },
  modalHeaderWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(0,86,210,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: T.navy,
  },
  modalSub: {
    fontSize: 10,
    color: T.textSub,
    fontWeight: '600',
    marginTop: 1,
  },
  inputLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: T.navy,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    marginBottom: 6,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e2e5ef',
    borderRadius: 16,
    paddingHorizontal: 14,
    height: 52,
    backgroundColor: '#f8f9fc',
    marginBottom: 24,
  },
  textInput: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: T.navy,
  },
  btnRow: {
    flexDirection: 'row',
    gap: 12,
  },
  cancelBtn: {
    flex: 1,
    backgroundColor: '#f1f3f9',
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    height: 50,
  },
  cancelBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: T.textSub,
  },
  actionBtn: {
    flex: 1.5,
    borderRadius: 16,
    overflow: 'hidden',
  },
  actionBtnGradient: {
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionBtnText: {
    fontSize: 13,
    fontWeight: '800',
    color: 'white',
  },
  // Scanner styles
  overlayContainer: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'space-between',
    zIndex: 10,
  },
  overlayTop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.65)',
  },
  overlayMiddle: {
    flexDirection: 'row',
    height: 240,
  },
  overlaySide: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.65)',
  },
  scanWindow: {
    width: 240,
    height: 240,
    backgroundColor: 'transparent',
    position: 'relative',
  },
  overlayBottom: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.65)',
    alignItems: 'center',
    paddingTop: 20,
  },
  overlayText: {
    color: '#cbd5e1',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 24,
  },
  torchBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
  },
  torchBtnText: {
    color: 'white',
    fontSize: 11,
    fontWeight: '800',
    marginLeft: 6,
  },
  // Corners
  corner: {
    position: 'absolute',
    width: 24,
    height: 24,
    borderColor: '#f5a623',
    borderWidth: 0,
  },
  topLeft: {
    top: 0,
    left: 0,
    borderTopWidth: 4,
    borderLeftWidth: 4,
    borderTopLeftRadius: 12,
  },
  topRight: {
    top: 0,
    right: 0,
    borderTopWidth: 4,
    borderRightWidth: 4,
    borderTopRightRadius: 12,
  },
  bottomLeft: {
    bottom: 0,
    left: 0,
    borderBottomWidth: 4,
    borderLeftWidth: 4,
    borderBottomLeftRadius: 12,
  },
  bottomRight: {
    bottom: 0,
    right: 0,
    borderBottomWidth: 4,
    borderRightWidth: 4,
    borderBottomRightRadius: 12,
  },
  laserLine: {
    position: 'absolute',
    left: 4,
    right: 4,
    height: 2,
    backgroundColor: '#f5a623',
    shadowColor: '#f5a623',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 2,
  }
});
