-- Purge sensitive secret keys and tokens from app_settings
-- Keep only public/app configurations (referral settings, branding, vendor selector, URLs)
-- Sensitive keys are securely held in public.system_secrets under strict admin RLS.

DELETE FROM public.app_settings
WHERE UPPER(key) IN (
    'AGENTHUB_API_KEY', 'AGENTHUB_KEY', 'AGENTS_HUB_KEY', 'AH_API_KEY',
    'BILALSADASUB_TOKEN', 'BILAL_TOKEN', 'BILALSADASUB_API_KEY', 'BILAL_API_KEY', 'BILALSADASUB_KEY',
    'PAYSTACK_SECRET_KEY', 'PAYSTACK_KEY', 'PAYSTACK_SECRET', 'PAYSTACK_API_KEY',
    'FLUTTERWAVE_SECRET_KEY', 'FLUTTERWAVE_KEY', 'FLUTTERWAVE_SECRET_HASH',
    'PAYVESSEL_API_SECRET', 'PAYVESSEL_SECRET_KEY', 'PAYVESSEL_SECRET', 'PAYVESSEL_API_KEY', 'PAYVESSEL_KEY', 'PAYBESSEL_API_KEY',
    'MONNIFY_API_KEY', 'MONNIFY_KEY', 'MONNIFY_SECRET_KEY', 'MONNIFY_SECRET',
    'BIGI_API_TOKEN', 'BIGI_TOKEN', 'BIGI_API_PIN', 'BIGI_PIN',
    'CLUBKONNECT_API_KEY', 'CLUBKONNECT_KEY', 'CLUBKONNECT_USER_ID', 'CLUBKONNECT_USER',
    'TERMII_API_KEY', 'TERMII_KEY',
    'OPENAI_API_KEY', 'OPENAI_KEY',
    'NINEBOOST_API_KEY', 'NINE_BOOST_API_KEY', 'NINEBOOST_KEY', 'NINE_BOOST_KEY',
    'NOWPAYMENTS_API_KEY', 'NOWPAYMENTS_KEY', 'NOWPAYMENTS_IPN_SECRET',
    'RESEND_API_KEY', 'RESEND_KEY',
    'ZOHO_PASSWORD', 'SMTP_PASS',
    'SUMSUB_SECRET_KEY', 'SUMSUB_APP_TOKEN'
);
